language: objective-c
rvm:
  - 2.4.3
cache: bundler

# Whitelist `master` branch as the only branch to build pushes for.
branches:
  only:
    - master

matrix:
  include:
    - osx_image: xcode10.2
      env: SDK=iphonesimulator PLATFORM="iOS Simulator,name=iPhone X,OS=12.2" SCHEME=Contentful_iOS
    - osx_image: xcode10.2
      env: SDK=appletvsimulator PLATFORM="tvOS Simulator,name=Apple TV,OS=12.2" SCHEME=Contentful_tvOS
    - osx_image: xcode10.2
      env: SDK=macosx PLATFORM="macOS" SCHEME=Contentful_macOS
    - osx_image: xcode10.2
      env: SWIFT_BUILD=true
      
script:
  - ./Scripts/travis-build-test.sh
after_success:
  - ./Scripts/integration-test.sh
  - bundle exec slather coverage -s --coveralls
  - bundle exec pod lib lint Contentful.podspec

env:
  global:
    - secure: JLkG75LSPkXdxZ4DRmjdvcie+YbOx1mkf2b7Ddny4dFYivw1nAQtJYTsqgog/hYwzxxGYD+93DiXkm4ElvxwHLq19s4aCuQY3uu3PO/N8gTqcJpsGfcFFkyqhEjpKrJKuWtLLS78CjXnfeRvIT7wT0nySvqotRZ4pOGZnCiEqOkGXjUv/eI9d4YZu4VVu46OMS27kTOV7CoeHhWiXV5L+owU8t3gffIpuuhkKr4LDtl/VhjdVmmwwDWjEfSNflCo0T/XiFNEF5mmF86BI5njjU0RVzmcRwWOjqgvA0nrvarae6SVn/QZC6JZutG+pKWWoSOAollbAXwjxcLIYMF/wIRXc3NJrS4VGW+Z2ORojcdbosoohPVrnayOy4Szq+I8Afa1dIQ+vYq2JxWuaOA2X+Toy9m81svIaE7CLNMK52aA0z8fOQFwFUAmFGOKVtHtiYkHcItUuFk7+c0feekfvmDsawtgACXTIUua6DIq0g54QTc9PidxGQti2kXoqRBaKzpGSbbMHIxh0A6wnPw9r/+26y8nipATNBmKbkwKOuLm6M4eMKRpvGNncv9z4zM66DAQH8EA5A92Qt9g1ETXeC+R9+SUd8r8ryFr/hr0jpjXEuk0aanM7BuLAjCFDXdQKFbjOtpR0ary6GNQK0FdGSmxKku1CXaUH9gNWg1cKpU=
    - secure: gpYcun1Nr0aDkggVr3OhR16gopoiOIVTUnk6oYFBmFWQDWPxzWOb5lc+oz5TJIhER5b1J6vl7sSXq8hAybBdy5fDRDHhJ7t5DvNc3DWhhTUr11gLzhG2kkCuKemMhJXR87l0+Kz94NfVmnJKw8TEfetrc6/cpJnQSYBjIfEZkdxkIy35jLt5AOeEyokchJg75891mtkcZa69iOBqf9tBhPAOigQQmAzVkKbxgkz0WA69KhhankJbZuOmySpTrWxFI/slz8j+Dj1wAcLqqbHWajjThJzBWXupg2CugyASuVBtQPJgKP9wo/F5dIDY/LreXoJUbfrxcEjLc54SX5A3cuq//H6/EDMGOxTr3YyhxL/Ba4r9nZomT1CwcRd2vrWPDmfnOtaImNzbhZxpU7O3M6kOwwnZD7Bl2isPer0sMuBfqdsL04HdQJIKZSrjgsGPKf6Ss2GKKKZIdGHX/i3X2c+S7cph5Vw/42I56WvRMm5S/7jn7DYTgZTAYN2plWrYSdjiVlXjsfz4aR1SEYzcIQ8Gh/J+ZOK2t0OkIqDvdQT+hKTUOCtBN7MSzGNRhfoQghKIETz6M9VlNCJ3yG3O3eMEi7UcozNKRrTGzULtWqp9Dmw9Pkb3xYWVaCLFW2GWPUaM7n7td7kBsubEIYzkz7I+KqhPMoesl/UYMSTaFYU=

