language: objective-c
osx_image: xcode8
script:
- xcodebuild -workspace Contentful.xcworkspace -scheme Contentful test -sdk iphonesimulator
- bundle exec slather coverage --coveralls Contentful.xcodeproj
- pod lib lint Contentful.podspec
