apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contentful.swift 
  description: Swift library for the Contentful Content Delivery API and Content Preview API.
  annotations:
    github.com/project-slug: contentful/contentful.swift 
    contentful.com/service-tier: "4"
  tags:
    - tier-4
spec:
  type: library 
  lifecycle: production
  owner: group:team-developer-experience
