# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test_ios do
    # test ios
    scan(
      scheme: "Contentful_iOS",
      clean: true,
    )
  end

  desc "Description of what the lane does"
  lane :test_macos do
    # test macos
    scan(
      scheme: "Contentful_macOS",
      clean: true,
    )
  end

  desc "Description of what the lane does"
  lane :test_tvos do
    # test tvos
    scan(
      scheme: "Contentful_tvOS",
      clean: true,
    )
  end

  desc "Description of what the lane does"
  lane :build do
    # verify project builds
    sh("cd .. && swift build")
  end
end
